### ISSUE TITLE
URL do artigo Aplicativos Espiões na Copa do Catar sobre catar fora do padrão

### ISSUE THREAD

**Issue by celsobessa** [celsobessa/tecnologia-humanista-artigos#2]
A URL do artigo Aplicativos Espiões na Copa do Catar esta fora do padrão: 

https://github.com/celsobessa/tecnologia-humanista-artigos/blob/20bee41c497ef1ce2058f6ad91dd8e2d02119817/pt/aolicativos-espioes-na%3Dcopa-docatar.md

O ideal seria `aplicativos-espioes-na-capa-do-catar.md`

**Comment by BitiAverbach** [comment]
não sei como colei essa url enorme e não percebi. foi mal rs. agora, no entanto, não estou conseguindo editar nada do arquivo. só consigo visualizar. qdo clico no ícone do lápis, não abre a tela da edição.
