### ISSUE TITLE
Utilizar aspas em citação/trecho de um terceiro.

### ISSUE THREAD

**Issue by celsobessa** [celsobessa/tecnologia-humanista-artigos#3]
Utilizar aspas nos textos de tercieros deixar claro que é citação/trecho escrito por uma fonte externa.

**Comment by BitiAverbach** [comment]
Ok, combinado!





Biti Averbach
Editora de conteúdo, Acessibilidade & SEO
Lifestyle, moda, beleza
cel. 32 99829-3305
bitiaverbach.com.br
